### ISSUE TITLE
Data error in celebahqedge

### ISSUE THREAD

**Issue by PP-dog** [microsoft/CoCosNet#14]
The input edge image style can't match with paper 
code generate edge image style
![image](https://user-images.githubusercontent.com/38178418/88364692-4d216e80-cdb6-11ea-8030-c6b7b06fc0c6.png)

paper's edge image style
![image](https://user-images.githubusercontent.com/38178418/88364838-c6b95c80-cdb6-11ea-81c3-811fc3158dae.png)

**Comment by panzhang0212** [comment]
hi, what's your version of scikit-image? I found some version of scikit-image 
https://github.com/microsoft/CoCosNet/blob/33f98d092407094a15a08b0555d6f5359490cd3e/data/celebahqedge_dataset.py#L106 
return all zeros(no canny edge output), such make style be similar to yours.
