### ISSUE TITLE
bad corr result's but good translation result's

### ISSUE THREAD

**Issue by PP-dog** [microsoft/CoCosNet#16]
I trained on celebahqedge dataset with two gpus，the results of corr is to bad, but translation can generator got good results。I found that only adaptive_kernel and batchsize is different between the two models.
our results
![image](https://user-images.githubusercontent.com/38178418/90586573-164e4500-e20a-11ea-9cc5-b49c1afc23d9.png)

your checkpoints results
![image](https://user-images.githubusercontent.com/38178418/90586653-4ac20100-e20a-11ea-8ba4-cbc85cc1b6d2.png)

**Comment by panzhang0212** [comment]
I never encountered this problem, the third row of your results have a distortion pattern. It's very strange, maybe you try with larger batch size.
