### ISSUE TITLE
great work ,but how to generate pose data in using openpose in custom datasets

### ISSUE THREAD

**Issue by dayu1979** [microsoft/CoCosNet#20]
I find there are 2 files,_additional_candidate and subset
but i dont know the details.
thanks.

**Comment by panzhang0212** [comment]
if you use the repo https://github.com/Hzzone/pytorch-openpose to extract the pose, _additional_candidate and subset will be saved.
file subset is the index of joints, and file _additional_candidate saves the location (x,y) of the joints in the file subset
