### ISSUE TITLE
How to convert ade20k color label to gray values used in CoCosNet

### ISSUE THREAD

**Issue by Peu-m** [microsoft/CoCosNet#22]
@panzhang0212 

Thank You for the codes for CoCosNet, results looks very impressive too.

However, i just wanted to use CoCosNet for new images using your ADE20K model, but when i infer with semantic segmentation model i get color labels as in ADE20K dataset.

As i understand CoCosNet ADE20k model will need gray mask for inference.
When i convert color ADE20K semantic mask using cv2 i don't get the labels used in your examples.

Therefore how do i convert color semantic labels given in ADE20k to gray labels used in your model ?

Best regards,
Peu

**Comment by panzhang0212** [comment]
Hi, you need change rgb mask to a single-channel image by class mapping between rgb and label index,
map be https://github.com/CSAILVision/semantic-segmentation-pytorch/issues/7 can help you

**Comment by Peu-m** [comment]
@panzhang0212 

Thank You for the information, i'm closing this issue.

Best
