### ISSUE TITLE
How to transform openpose JSON file to candidate.txt and subset.txt in the pose-to-image?

### ISSUE THREAD

**Issue by JunFang-NWPU** [microsoft/CoCosNet#26]
Hi,

Thanks for sharing the project. I want to use openpose to generate my own dataset for pose-to-image. Openpose will output a JSON file (https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md) which is very different with candidate.txt and subset.txt included in the CoCosNet project.

What's the relationship between the openpose JSON file and candidate.txt & subset.txt? How to transform from one to another?

Thanks.

**Comment by panzhang0212** [comment]
You can use https://github.com/Hzzone/pytorch-openpose to extract pose, which will save candidate.txt & subset.txt. Or you can change the code to read your version.
