### ISSUE TITLE
Pretrained_VGG

### ISSUE THREAD

**Issue by sunwoo76** [microsoft/CoCosNet#28]
Hi, first of all, I appreciate your work.

For using your model, I wonder the weights of VGG19 at this link 'https://drive.google.com/file/d/1fp7DAiXdf0Ay-jANb8f0RHYLTRyjNv4m/view', which you posted on README.

Is this VGG weight file the same thing that is posted in torchvision in Pytorch?

thanks.

**Comment by zhangmozhe** [comment]
Hi sorry for the late reply. This is the VGG weight pretrained by caffe. We empirically find that this pretrained model gives better visual quality than the official pytorch pretrained VGG. You can optimize an image to reconstruct itself by minimizing relu5.2 to see that.

**Comment by sunshower76** [comment]
Thank you for replying.
And, This will be my last question.
This weight is pre-trained VGG by Caffe using the IMAGENET?
what dataset is used for pre-training?

**Comment by sunwoo76** [comment]
thank your reply!

**Comment by fnzhan** [comment]
Hi @panzhang0212,  @zhangmozhe .  For the semantic relevance,  high level feature relu_ 5_2 extracted by pre-trained vgg is adopted to  measure the cosines similarity,  the reported score is about 0.8  for most comparing models. I follow the the method,  using the pre-trained vgg model you provided, and the result is about 0.55,  may  I know more about the  evaluation of semantic relevance.

**Comment by panzhang0212** [comment]
please refer to #25, the semantic consistency code is  sc_vgg_metric.py, and the style relevance code is ref_vgg_metric.py. Both files are in evaluation.zip

**Comment by mlxht990720** [comment]
> please refer to #25, the semantic consistency code is sc_vgg_metric.py, and the style relevance code is ref_vgg_metric.py. Both files are in evaluation.zip

Could you please tell me the format of computing semantic consistency? I can't understand the example you post in evaluation.zip, that's "python/sc_vgg_metric.py/mnt/blob/Output/image_translation_methods/SPADE/output/test_per_img/ade20k_vae_v100 ade20k". what about ade20k_vae_v100 mean? I'm a beginner, many thanks!
