### ISSUE TITLE
the real_reference_probability and hard_reference_probability

### ISSUE THREAD

**Issue by neew123** [microsoft/CoCosNet#29]
Firstly, Thanks for your patient reply again！when I use CoCosNet train on my own edge-to-image dataset, the first twenty iterations it can generate good results, but when after twenty iterations, the translation result is the same as the exemplar but not use edge image to control pose. I try to find an answer in the paper but I can't. So, I want to ask what does the real_reference_probability and hard_reference_probability work? Can I change it to better match my own dataset?

**Comment by sunwoo76** [comment]
Hi, I am also using CoCosNet.
I could explain somewhat about the real or hard reference probability.

I used celebahq dataset.

I recommend you refer to 'data/celebahq_ref.txt'.
You could see many lines. Let's see the first line.
0.jpg is the source(the image of exemplar) and others could be a target.
but, in this code, 5792.jpg is used real_reference which is an easy example.
and the image 7254.jpg,which is at the last of the first line, is used hard reference.

In the paper, you could refer to the section3.3.
There is an image augmentation. I think that this part is related to real_reference(easy example).
Same image is used but it is augmented.

**Comment by panzhang0212** [comment]
Hi, the translation result is the same as the exemplar, we call this phenomenon identity mapping, a trivial solution.  There are three solutions:
1. decrease the weight of contextual loss
2. increase the weight of perceptual loss
3. If use cycle loss, decrease the weight of it.

**Comment by neew123** [comment]
> Hi, I am also using CoCosNet.
> I could explain somewhat about the real or hard reference probability.
> 
> I used celebahq dataset.
> 
> I recommend you refer to 'data/celebahq_ref.txt'.
> You could see many lines. Let's see the first line.
> 0.jpg is the source(the image of exemplar) and others could be a target.
> but, in this code, 5792.jpg is used real_reference which is an easy example.
> and the image 7254.jpg,which is at the last of the first line, is used hard reference.
> 
> In the paper, you could refer to the section3.3.
> There is an image augmentation. I think that this part is related to real_reference(easy example).
> Same image is used but it is augmented.

I understand it! thanks  for your explaining

**Comment by neew123** [comment]
> Hi, the translation result is the same as the exemplar, we call this phenomenon identity mapping, a trivial solution. There are three solutions:
> 
> 1. decrease the weight of contextual loss
> 2. increase the weight of perceptual loss
> 3. If use cycle loss, decrease the weight of it.

**Comment by YukunZEX** [comment]
hi, im trying to train cocosnet on my own dataset too. could you please tell me how did you prepare your own edge-to-image dataset? how do i generate label, ref,self_ref...
