### ISSUE TITLE
DeepFashion Training Pairs

### ISSUE THREAD

**Issue by RenYurui** [microsoft/CoCosNet#31]
Hi, 
Thanks for your awesome work.
I have a question about the DeepFashion training pairs. I read the code and found that the DeepFashion pairs are established by the 'deepfashion_self_pair.txt' and 'deepfashion_ref.txt'. I want to ask that how do you get these two files (especially the latter). Are there images in the DeepFashion dataset removed (as the number of images is not the same)?

**Comment by panzhang0104** [comment]
'deepfashion_self_pair.txt': the image paths in the same lines belong to one person with different poses. We get this information by the image name.
'deepfashion_ref.txt': for one line, the first image is key, other images are retrieved by the VGG feature.

As I know, these images are not removed,  (low resolution, not recently released high-resolution dataset)

**Comment by xinzi2018** [comment]
if i want to use other datasets to train , how can i get 'deepfashion_self_pair.txt' and 'deepfashion_ref.txt' ?
