### ISSUE TITLE
demo for makeup transfer?

### ISSUE THREAD

**Issue by puppet101** [microsoft/CoCosNet#4]
Hi, do you have any plan to release the code for makeup transfer? Or could you please explain the implementations in  detail?  Thank you!

**Comment by panzhang0212** [comment]
Hi, for detail of makeup transfer.
1.need a makeup layer image for source face. we use photoshop to get makeup layer image. This is the makeup image of figure 11 in our paper.
![2127](https://user-images.githubusercontent.com/30363822/85360711-7ac38f80-b54c-11ea-863d-7e05bf1fa2fd.png)
2.warp the makeup layer image by learnt dense correspondence between source face image(as exemplar) and target face image(edge, as input). https://github.com/microsoft/CoCosNet/blob/3db703a46f9969836037427e190ede8480c07ce1/models/networks/correspondence.py#L307 is learnt correspondence. The warping code:
![image](https://user-images.githubusercontent.com/30363822/85361514-b19aa500-b54e-11ea-824f-1a8f608ec039.png)
self.makeup is your orignial makeup layer image.
3.after getting warped makeup layer image, blend it with target face and get final output
   from blend_modes import multiply 
   multiply(target_face, makeup, 1)

**Comment by puppet101** [comment]
Thank you very much! I will have a try.

**Comment by mlxht990720** [comment]
Hi! I'm a beginner, I can't understand where the warping  code should be added and how to get final output , could you please tell me more?
