### ISSUE TITLE
Attention in SPADEGenerator

### ISSUE THREAD

**Issue by yf1019** [microsoft/CoCosNet#5]
Hi, I notice there is an attention model in the SPADEGenerator, which is defined in the CoCosNet/models/networks/architecture.py line 97. What does this model mean? Can you give a reference? Thanks a lot!

**Comment by panzhang0212** [comment]
we use attention model to get more globel feature to help synthesis. you can get more information in this paper https://arxiv.org/pdf/1711.07971.pdf

**Comment by yf1019** [comment]
> we use attention model to get more globel feature to help synthesis. you can get more information in this paper https://arxiv.org/pdf/1711.07971.pdf

Thanks!

**Comment by yf1019** [comment]
> we use attention model to get more globel feature to help synthesis. you can get more information in this paper https://arxiv.org/pdf/1711.07971.pdf

Hi, pan. This work can be used in many fileds. it's great! I just remembered another question. 
In the deepfashion dataset, you use the pose landmarks and their joints as input semantics. However, in the code, I noticed this
data/deepfashion.py
![a](https://user-images.githubusercontent.com/44568791/85667447-2e18b980-b6f0-11ea-98bc-afbd9f461cf2.JPG)
It seems you additionly compute one "distance map"  for every joint. What is the meaning of this? Is it used to add extra joint information to the model?

**Comment by panzhang0212** [comment]
the pose image is sparse, only pose landmarks and their joints have nonzero value, so we add distance map to give distance infomantion between zero pixel and joints. This pose representation is better for convolution operator.

**Comment by yf1019** [comment]
> the pose image is sparse, only pose landmarks and their joints have nonzero value, so we add distance map to give distance infomantion between zero pixel and joints. This pose representation is better for convolution operator.

I get it. Thanks a lot!
