### ISSUE TITLE
Domain alignment loss before channel-wise normalization

### ISSUE THREAD

**Issue by htzheng** [microsoft/CoCosNet#8]
https://github.com/microsoft/CoCosNet/blob/0acee3739094ddbd9c1dea203410ff54fc270df7/models/networks/correspondence.py#L249

In `correspondence.py`, the domain alignment loss seems to be computed before the channel-wise normalization. While it doesn't affect the model inference, it might cause trivial solutions during training (as suggested by Eq. 9 of the paper). Not sure if it is a bug to be fixed.

Many thanks!

**Comment by panzhang0212** [comment]
sorry, fix it.
