### ISSUE TITLE
How to use your model train or test other dataset?

### ISSUE THREAD

**Issue by sunshinewhy** [microsoft/CoCosNet#9]
Thanks for your awesome work. I want to use my own dataset to test your model. My dataset is an image dataset in the format of 1024X768 images. May I ask how I can pre-process the dataset to use your model? And can your pre-training model be used to test other datasets？

**Comment by panzhang0212** [comment]
1. our training resolution is 256x256
2.the pre processing can be found in `data/*_dataset.py`, depend on your dataset(mask-to-image. edge-to-face or pose-to-image)
3.different datsets may have domain gap, which makes model perform differently. But you can try it

**Comment by wanghongyu607** [comment]
@panzhang0212 May I ask NVIDIA GTX1070 can train your model?

**Comment by sunshinewhy** [comment]
@panzhang0212 I use your pre-train model test on my dataset, but the result is bad,  should I retrain the model and update the parameters?

**Comment by panzhang0212** [comment]
yeah, you need to train your dataset
